### ISSUE TITLE
linux-headers-4.4.0

### ISSUE THREAD

**Issue by mkoubar** [vel21ripn/nDPI#36]
/usr/src/nDPI/ndpi-netfilter/src/../../src/lib/ndpi_main.c:41:35: fatal error: ndpi_network_list.c.inc: No such file or directory
 #include "ndpi_network_list.c.inc"
                                   ^
compilation terminated.

**Comment by elico** [comment]
@mkoubar What OS are you using?
What kernel are you using? the distro or manually compiled?
What steps should I do to reproduce this issue on a VM?

**Comment by vel21ripn** [comment]
```
./autogen.sh
( cd src/lib ; make ndpi_network_list.c.inc )
( cd ndpi-netfilter ; make )
```

**Comment by panda-mute** [comment]
@vel21ripn 
It will cause some trouble in cross compile.
Host: x86
Target: arm

ndpi_network_list_compile need run in Host to generate ndpi_network_list.c.inc

**Comment by elico** [comment]
@vel21ripn It seems that it works on ubuntu 16.04 and this is the docker build node for it:
- http://gogs.ngtech.co.il/elicro/ubuntu1604-dev-ndpi-v2.2-vel
